version: '3'
services:
  reverse-proxy:
    hostname: reverse-proxy
    container_name: reverse-proxy
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  hello-nest:
    hostname: hello-nest
    container_name: hello-nest
    image: hello-nest
    ports:
      - :3000
    labels:
      - traefik.http.services.hello-nest.loadbalancer.server.port=3000
      - traefik.http.routers.hello-nest.rule=PathPrefix(`/nest`)
      - traefik.http.routers.hello-nest.middlewares=hello-nest-stripprefix
      - traefik.http.middlewares.hello-nest-stripprefix.stripprefix.prefixes=/nest
